services:
  rails-blue:
    image: chatwoot:custom-production
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: production
        BUNDLE_WITHOUT: development:test
        RAILS_SERVE_STATIC_FILES: 'true'
        EXECJS_RUNTIME: Disabled
    env_file: ../.env
    volumes:
      - storage_data:/app/storage
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '127.0.0.1:3001:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000/auth/sign_in || exit 1']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    profiles:
      - blue

  rails-green:
    image: chatwoot:custom-production
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: production
        BUNDLE_WITHOUT: development:test
        RAILS_SERVE_STATIC_FILES: 'true'
        EXECJS_RUNTIME: Disabled
    env_file: ../.env
    volumes:
      - storage_data:/app/storage
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '127.0.0.1:3002:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000/auth/sign_in || exit 1']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    profiles:
      - green

  sidekiq:
    image: chatwoot:custom-production
    env_file: ../.env
    volumes:
      - storage_data:/app/storage
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
    env_file: ../.env

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]
    env_file: ../.env
    volumes:
      - redis_data:/data

volumes:
  storage_data:
  postgres_data:
  redis_data:
